work_dir: ./checkpoints/prova
resume_from: None    # None | path

# training
device: [0,1]
batch_size: 256
test_batch_size: 128
num_epoch: 300
start_epoch: 0
stream: 'joint'

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [150, 250]

# log
log_interval: 25
save_interval: 25
eval_interval: -1
disable_wandb: True

# model
model_args:
  pretrain: True
  use_nnm: False
  queue_size: 32768
  time_dim: 50
  spat_dim: 25
  in_channels: 3
  hidden_channels: 32
  out_channels: 256
  hidden_layer: -1
  projection_hidden_size: [256, 128]
  predictor_hidden_size: [128, 128]
  moving_average_decay: 0.999
  use_momentum: True
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: False
  loss_name: 'cosine_sim'   # cosine_sim - mse

# nearest neighbor mining
topk: 1
mining_epoch: 10
lambda_mining: 0.9

# feeder
train_feeder_args:
  data_path: /data_volume/data/ntu60_aimclr/ntu60_frame50/xview/train_position.npy
  label_path: /data_volume/data/ntu60_aimclr/ntu60/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True