work_dir: ./checkpoints/byol_aimclr_hyper_prova
resume_from: None    # None | path

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: ./data/ntu60_aimclr/ntu60_frame50/xview/train_position.npy
  label_path: ./data/ntu60_aimclr/ntu60/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model_args:
  pretrain: True
  use_nnm: True
  queue_size: 32768
  time_dim: 50
  spat_dim: 25
  in_channels: 3
  hidden_channels: 32
  out_channels: 256
  hidden_layer: -1
  projection_hidden_size: [256, 128]
  hyperbolic_proj_mask: [0,1]
  predictor_hidden_size: [128, 128]
  hyperbolic_pred_mask: [1,1]
  moving_average_decay: 0.999
  use_momentum: True
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: False
  loss_name: 'poincare'   # cosine_sim - mse - poincare
  hyperbolic: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: RiemannianSGD # SGD - RiemannianSGD - RiemannianAdam
step: [100, 200]

# training
device: [2,5]
batch_size: 300
test_batch_size: 128
num_epoch: 300
start_epoch: 0
stream: 'joint'

# nearest neighbor mining
topk: 1
mining_epoch: 1000
lambda_mining: 0.9

# log
log_interval: 25
save_interval: 25
eval_interval: -1
disable_wandb: False