work_dir: ./checkpoints/debug_stgcn

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: ./data/ntu60_aimclr/ntu60_frame50/xview/train_position.npy
  label_path: ./data/ntu60_aimclr/ntu60/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.siam_aimclr.SiameseAimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: True
  feature_dim: 1024
  momentum: 0.999
  mlp: True
  in_channels: 3
  hidden_channels: 64 # 1/4 x channels of standard stgcn
  hidden_dim: 1024
  num_class: 60
  dropout: 0.5
  proj_depth: 2
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: False

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
lr_scheduler: cosine
step: [80, 150]

# training
device: [0,1]
batch_size: 512
test_batch_size: 128
num_epoch: 300
start_epoch: 0
stream: 'joint'

# log
save_interval: 1
eval_interval: -1
disable_wandb: False
