work_dir: ./checkpoints/byol_aimclr_nnm_lt
resume_from: ./checkpoints/byol_aimclr_huge_sgd/epoch250_model.pt    # None | path

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: ./data/ntu60_aimclr/ntu60_frame50/xview/train_position.npy
  label_path: ./data/ntu60_aimclr/ntu60/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model_args:
  pretrain: True
  queue_size: 16384
  time_dim: 50
  spat_dim: 25
  in_channels: 3
  hidden_channels: 64
  out_channels: 1024
  hidden_layer: -1
  projection_hidden_size: [1024, 1024]
  predictor_hidden_size: [1024, 1024]
  moving_average_decay: 0.999
  use_momentum: True
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: False
  loss_name: 'cosine_sim'   # cosine_sim - mse

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.001
optimizer: SGD
step: [100, 250]

# training
device: [4,6]
batch_size: 256
test_batch_size: 128
num_epoch: 150
start_epoch: 0
stream: 'joint'

# nearest neighbor mining
topk: 1
mining_epoch: 10
lambda_mining: 0.9

# log
log_interval: 25
save_interval: 10
eval_interval: -1
disable_wandb: False