work_dir: ./checkpoints/aimclr_neg_dev

# feeder
train_feeder: feeder.ntu_feeder.Feeder_triple
train_feeder_args:
  data_path: ./data/ntu60_aimclr/ntu60_frame50/xview/train_position.npy
  label_path: ./data/ntu60_aimclr/ntu60/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  mmap: True

# model
model: net.siam_neg_aimclr.SiameseNegAimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: True
  feature_dim: 128
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  proj_depth: 2
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: False

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [250]

# training
device: [3]
batch_size: 32
test_batch_size: 128
num_epoch: 300
start_epoch: 0
stream: 'bone'   # joint | motion | bone

# nearest neighbor mining
topk: 1
mining_epoch: 150

# log
save_interval: 25
eval_interval: -1
disable_wandb: True