work_dir: ./checkpoints/linear_joint_xview

weights: ./checkpoints/agcn/epoch50_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue, predictor]


# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: ./data/ntu60_aimclr/ntu60_frame50/xview/train_position.npy
  label_path: ./data/ntu60_aimclr/ntu60/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: ./data/ntu60_aimclr/ntu60_frame50/xview/val_position.npy
  label_path: ./data/ntu60_aimclr/ntu60/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.siam_aimclr.SiameseAimCLR
model_args:
  base_encoder: net.agcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  # hidden_channels: 64 # 16
  hidden_dim: 256
  num_class: 60
  # dropout: 0.5
  # proj_depth: 3
  graph_args:
    labeling_mode: 'spatial'
  edge_importance_weighting: False

# optim
nesterov: False
weight_decay: 0.0
base_lr: 0.05
optimizer: SGD
step: [30, 60] #[10, 60, 90]

# training
device: [0,1]
batch_size: 256
test_batch_size: 256
num_epoch: 100
stream: 'joint'

# log
save_interval: -1
eval_interval: 5
