work_dir: ./checkpoints/linear_byol_aimclr_joint_xview
weights: ./checkpoints/byol_aimclr_nnm_lt/epoch=149-step=22049.ckpt
ignore_weights: [online_encoder.projector, target_encoder, online_predictor, queue]

# training
device: [4,6]
batch_size: 512
test_batch_size: 128
num_epoch: 100
stream: 'joint'   # joint | motion | bone

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: ./data/ntu60_aimclr/ntu60_frame50/xview/train_position.npy
  label_path: ./data/ntu60_aimclr/ntu60/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: ./data/ntu60_aimclr/ntu60_frame50/xview/val_position.npy
  label_path: ./data/ntu60_aimclr/ntu60/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.byol_aimclr_lightning.BYOLAimCLR
model_args:
  base_encoder: net.st_gcn_no_proj.Model
  pretrain: False
  time_dim: 50
  spat_dim: 25 
  in_channels: 3
  hidden_channels: 64
  out_channels: 1024
  hidden_layer: -1
  projection_hidden_size: [60]
  hyperbolic_proj_mask: [1]
  # projection_size: 60
  # predictor_hidden_size: 1024
  # moving_average_decay: 0.999
  # use_momentum: True
  # dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: False

# optim
nesterov: False
weight_decay: 0.0
base_lr: 0.5
optimizer: SGD
step: [30, 60]

# log
save_interval: -1
eval_interval: 5
